FROM golang:1.18-alpine as image2disk
RUN apk add --no-cache git ca-certificates gcc linux-headers musl-dev
COPY image2disk/v1 /go/src/github.com/tinkerbell/hub/actions/image2disk/v1
COPY common /go/src/github.com/tinkerbell/hub/actions/common
COPY go.mod /go/src/github.com/tinkerbell/hub/actions/go.mod
COPY go.sum /go/src/github.com/tinkerbell/hub/actions/go.sum
WORKDIR /go/src/github.com/tinkerbell/hub/actions
ENV GO111MODULE=on
RUN GOPRIVATE=github.com/tinkerbell/\*,github.com/platinasystems/\* go mod download
WORKDIR /go/src/github.com/tinkerbell/hub/actions/image2disk/v1
RUN --mount=type=cache,sharing=locked,id=gomod,target=/go/pkg/mod/cache \
    --mount=type=cache,sharing=locked,id=goroot,target=/root/.cache/go-build \
    CGO_ENABLED=1 GOOS=linux go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o image2disk

# Build final image
FROM scratch
# Add Certificates into the image, for anything that does HTTPS calls
COPY --from=image2disk /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=image2disk /go/src/github.com/tinkerbell/hub/actions/image2disk/v1/image2disk .
ENTRYPOINT ["/image2disk"]
